services:
  base:
    build: ./base
    tty: true
    env_file: .env
    volumes:
      - ./base:/home
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]