# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
╭$directory$git_branch$git_status$git_state$python$go$conda $fill $cmd_duration$time$battery
╰$character
"""

[aws]
symbol = " "
format = '@ [$symbol(\($region\) $duration)]($style)'
disabled = true

[character]
error_symbol = '[✗](bold red) '

[conda]
symbol = " "
format = 'via [$symbol$environment]($style) '
ignore_base = false

[directory]
read_only = " 󰌾"
truncation_length = 3
format = '[$read_only]($read_only_style) [$path]($style) '
truncate_to_repo = false
repo_root_style = "bold cyan"
before_repo_root_style = "dimmed bright-black"

[docker_context]
symbol = " "

[fill]
symbol = ' '

[git_branch]
symbol = " "
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[line_break]
disabled = false

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "
format = 'via [${symbol}$virtualenv ]($style)'
python_binary = ['./venv/bin/python', 'python3']

[sudo]
disabled = true

[time]
disabled = false
time_format = '%T'
