# Kanagawa Wezterm Colors
# Upstream: https://github.com/rebelot/kanagawa.nvim/

[colors]
ansi = [
  "#090618",
  "#c34043",
  "#87a987",
  "#c0a36e",
  "#8ba4b0",
  "#957fb8",
  "#6a9589",
  "#c8c093",
]
brights = [
  "#727169",
  "#e82424",
  "#98bb6c",
  "#e6c384",
  "#7fb4ca",
  "#938aa9",
  "#7aa89f",
  "#dcd7ba",
]
background = '#363646'
foreground = '#dcd7ba'
cursor_bg = '#c8c093'
cursor_fg = '#1f1f28'
cursor_border = '#c8c093'
selection_bg = '#2d4f67'
selection_fg = '#c8c093'
scrollbar_thumb = '#16161d'
split = '#c8c093'

[colors.indexed]
16 = '#ffa066'
17 = '#ff5d62'

[metadata]
name = 'kanagawa'
origin_url = 'https://github.com/rebelot/kanagawa.nvim/blob/master/extras/wezterm.lua'
