# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  # Selection
  { on = "<C-i>", run = "select_all --state=none", desc = "Inverse selection of all files" },

  # Tabs
  { on = [
    "<Tab>",
    "<Tab>",
  ], run = "tab_create --current", desc = "Create a new tab with CWD" },

  { on = [
    "g",
    "f",
  ], run = "plugin --sync first-non-directory", desc = "Jump to the first file" },
]

[input]

prepend_keymap = [{ on = "<Esc>", run = "close", desc = "Cancel input" }]
